title: "コマンドでたたかう！RPGゲームをつくろう"
summary: "小学生高学年向けに、Pythonでコマンド入力型のRPGゲームを作る教材です。勇者になって敵を倒す冒険に出かけよう！"
topics: ["python", "rpg", "ゲーム制作", "プログラミング教育"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"
  - "06"
  - "07"
  - "08"
