title: "pygameで迷路ゲームを作ろう"
summary: "小学生向けに作成した資料です。"
topics: ["pygame", "迷路ゲーム", "ゲーム制作"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"
  - "06"
  - "07"
  - "08"
  - "main"
